modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GENERAL PUBLIC LICENSE"

[[mods]]
modId = "easybreeding"
version = "${version}"
displayName = "EasyBreeding"
authors = "Gigabit101, Icynewyear"
description = '''
Easy Breeding adds the ability to breed animals (excepting Ocelots and Wolves) by tossing their breeding food on the ground near them.
'''
#logoFile = ""

[[dependencies.easybreeding]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easybreeding]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
