modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "GNU GENERAL PUBLIC LICENSE"

[[mods]]
modId = "autobreed"
version = "${version}"
displayName = "AutoBreed"
authors = "VoidNull, Gigabit101, Icynewyear"
description = '''
Easy Breeding adds the ability to breed animals (excepting Ocelots and Wolves) by tossing their breeding food on the ground near them.
'''
#logoFile = ""

[[dependencies.autobreed]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.autobreed]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
